name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to the gitcord repository. Thank you for sharing your Issue <3 We will try our best to review and label your issue promptly!"
        pr-message: "Welcome to the gitcord repository. Thank you for making a Pull Request <3 We will try our best to review your PR promptly!"
